### Get all posts

GET http://localhost:8000/api/v1/posts
Content-Type: application/json
Accept: application/json


### Create a new post
POST http://localhost:8000/api/v1/posts
Content-Type: application/json
Accept: application/json

{
    "title": "Post 2",
    "content": "Content 2",
    "author_id": 4
}

### Show a post
GET http://localhost:8000/api/v1/posts/1
Content-Type: application/json
Accept: application/json


### Update a post
PUT http://localhost:8000/api/v1/posts/1
Content-Type: application/json
Accept: application/json

{
    "title": "Post 1 Updated",
    "content": "Content 1 Updated"
}

### Delete a post                       

DELETE http://localhost:8000/api/v1/posts/1
Content-Type: application/json
Accept: application/json

