### Get all posts

GET http://localhost:8000/api/v1/posts?page=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|MjT8gXtGVI1jwIl5XamQjDUA6PNM33IWZLnIHd1J37b71873


### Create a new post
POST http://localhost:8000/api/v1/posts
Content-Type: application/json
Accept: application/json

{
    "title": "Title 3",
    "content": "Content 3",
    "author_id": 1
}


### Show a post
GET http://localhost:8000/api/v1/posts/1
Content-Type: application/json
Accept: application/json


### Update a post
PUT http://localhost:8000/api/v1/posts/1
Content-Type: application/json
Accept: application/json

{
    "title": "Post 2 Updated",
    "content": "Content 1 Updated"
}

### Delete a post                       

DELETE http://localhost:8000/api/v1/posts/1
Content-Type: application/json
Accept: application/json


### Register a new user
POST http://localhost:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Maruf Rahman",
    "email": "maruf@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678"
}


### Login a user
POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "maruf@gmail.com",
    "password": "12345678"
}


### Logout a user
POST http://localhost:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|teoSsZDCDyN7VrKzkGYoYmbfo7A74aVxHBj88orI654bdcae

